{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0.0",
    "title" : "SwaggerHub Sample",
    "description" : "A sample API for working with SwaggerHub"
  },
  "basePath" : "/v1",
  "host" : "localhost:8080",
  "schemes" : [ "http" ],
  "paths" : {
    "/people" : {
      "post" : {
        "tags" : [ "People" ],
        "operationId" : "addPeople",
        "parameters" : [ {
          "in" : "body",
          "name" : "person",
          "schema" : {
            "$ref" : "#/definitions/Person"
          },
          "required" : true
        } ],
        "responses" : {
          "default" : {
            "description" : "great job!"
          }
        }
      },
      "get" : {
        "tags" : [ "People" ],
        "operationId" : "findPeople",
        "description" : "\"Gets `Person` objects.\nOptional query param of **size** determines\"\n",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "skip",
          "in" : "query",
          "description" : "records to skip",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "max records to return",
          "required" : true,
          "type" : "integer",
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful response, empty if no results",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Person"
              }
            }
          }
        }
      }
    },
    "/people/{id}" : {
      "get" : {
        "tags" : [ "People" ],
        "operationId" : "getPersonById",
        "description" : "Finds a person by id",
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "ID of the user to fetch",
          "default" : "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        } ],
        "responses" : {
          "200" : {
            "description" : "person requested",
            "schema" : {
              "$ref" : "#/definitions/Person"
            }
          },
          "400" : {
            "description" : "person could not be found"
          }
        }
      }
    }
  },
  "definitions" : {
    "Person" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "description" : "The unique user identifier",
          "readOnly" : true,
          "type" : "string",
          "format" : "uuid",
          "example" : "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        },
        "firstname" : {
          "description" : "person's first name",
          "type" : "string",
          "example" : "Fred"
        },
        "lastname" : {
          "type" : "string",
          "example" : "Meyer"
        },
        "single" : {
          "type" : "boolean",
          "example" : false
        },
        "address" : {
          "$ref" : "#/definitions/Address"
        },
        "pets" : {
          "type" : "array",
          "items" : {
            "$ref" : "myPojos.json#/Pet"
          }
        }
      }
    },
    "Address" : {
      "type" : "object",
      "properties" : {
        "street" : {
          "description" : "the street name, line 1",
          "type" : "string",
          "example" : "12894 El Monte Blvd."
        },
        "city" : {
          "description" : "the cit",
          "type" : "string",
          "example" : "Los Altos Hills"
        },
        "state" : {
          "description" : "The two-character state",
          "minLength" : 2,
          "maxLength" : 2,
          "type" : "string",
          "example" : "CA"
        },
        "zip" : {
          "description" : "Zip code, Zip+4 allowed",
          "type" : "string",
          "example" : 94022
        }
      }
    }
  }
}